version: "2.2"

services:
  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    ports:
         - "5432:5432"
  
      
      